a=input()
if a=="fdsajkl;" or a=="jkl;fdsa":print("in-out")
elif a=="asdf;lkj" or a==";lkjasdf":print("out-in")
elif a=="asdfjkl;":print("stairs")
elif a==";lkjfdsa":print("reverse")
else:print("molu")